# Generated by Django 5.2.1 on 2025-10-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
    ]
