# Generated by Django 5.2.1 on 2025-10-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_telegramotp_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramotp',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramotp',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
