# Generated by Django 5.2.1 on 2025-10-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_alter_telegramotp_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedvideo',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
