# Generated by Django 5.2.1 on 2025-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_downloadedvideo_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedvideo',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
